DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS user_account;
DROP TABLE IF EXISTS books

CREATE TABLE post (
    post_id INT GENERATED ALWAYS AS IDENTITY,
    title VARCHAR (100) NOT NULL,
    content VARCHAR (500) NOT NULL,
    PRIMARY KEY (post_id)
);

CREATE TABLE user_account (
    user_id INT GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(30) UNIQUE NOT NULL,
    password CHAR(60) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE token (
    token_id INT GENERATED ALWAYS AS IDENTITY,
    user_id INT NOT NULL,
    token CHAR(36) UNIQUE NOT NULL,
    PRIMARY KEY (token_id),
    FOREIGN KEY (user_id) REFERENCES user_account("user_id")
);

CREATE TABLE books (
    book_id INT GENERATED ALWAYS AS IDENTITY,
    book_name VARCHAR(100) NOT NULL,
    content VARCHAR(5000) NOT NULL,
    book_year INT NOT NULL,
    author VARCHAR(250) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    on_loan BOOLEAN
);

INSERT INTO books VALUES (1,'Harry Potter and the Sorcerer’s Stone',"The book is about 11 year old Harry Potter, who receives a letter saying that he is invited to attend Hogwarts, school of witchcraft and wizardry. He then learns that a powerful wizard and his minions are after the sorcerer's stone that will make this evil wizard immortal and undefeatable.", 1997,'J.K Rowling', 'Fantasy', TRUE);
INSERT INTO books VALUES (2, 'Alice"s Adeventures in Wonderland', "The story centres on Alice, a young girl who falls asleep in a meadow and dreams that she follows the White Rabbit down a rabbit hole. She has many wondrous, often bizarre adventures with thoroughly illogical and very strange creatures, often changing size unexpectedly (she grows as tall as a house and shrinks to 3 inches [7 cm]). She encounters the hookah-smoking Caterpillar, the Duchess (with a baby that becomes a pig), and the Cheshire Cat, and she attends a strange endless tea party with the Mad Hatter and the March Hare. She plays a game of croquet with an unmanageable flamingo for a croquet mallet and uncooperative hedgehogs for croquet balls while the Queen calls for the execution of almost everyone present. Later, at the Queen’s behest, the Gryphon takes Alice to meet the sobbing Mock Turtle, who describes his education in such subjects as Ambition, Distraction, Uglification, and Derision. Alice is then called as a witness in the trial of the Knave of Hearts, who is accused of having stolen the Queen’s tarts. However, when the Queen demands that Alice be beheaded, Alice realizes that the characters are only a pack of cards, and she then awakens from her dream", 1865, "Lewis Carroll", "Adventure Fantasy", FALSE);
INSERT INTO books VALUES (3, 'To Kill a Mockingbird', "To Kill a Mockingbird takes place in the fictional town of Maycomb, Alabama, during the Great Depression. The protagonist is Jean Louise (“Scout”) Finch, an intelligent though unconventional girl who ages from six to nine years old during the course of the novel. She is raised with her brother, Jeremy Atticus (“Jem”), by their widowed father, Atticus Finch. He is a prominent lawyer who encourages his children to be empathetic and just. He notably tells them that it is “a sin to kill a mockingbird,” alluding to the fact that the birds are innocent and harmless. When Tom Robinson, one of the town’s Black residents, is falsely accused of raping Mayella Ewell, a white woman, Atticus agrees to defend him despite threats from the community. At one point he faces a mob intent on lynching his client but refuses to abandon him. Scout unwittingly diffuses the situation. Although Atticus presents a defense that gives a more plausible interpretation of the evidence—that Mayella was attacked by her father, Bob Ewell—Tom is convicted, and he is later killed while trying to escape custody. A character compares his death to “the senseless slaughter of songbirds,” paralleling Atticus’s saying about the mockingbird. The children, meanwhile, play out their own miniaturized drama of prejudice and superstition as they become interested in Arthur (“Boo”) Radley, a reclusive neighbour who is a local legend. They have their own ideas about him and cannot resist the allure of trespassing on the Radley property. Their speculations thrive on the dehumanization perpetuated by their elders. Atticus, however, reprimands them and tries to encourage a more sensitive attitude. Boo makes his presence felt indirectly through a series of benevolent acts, finally intervening when Bob Ewell attacks Jem and Scout. Boo kills Ewell, but Heck Tate, the sheriff, believes it is better to say that Ewell’s death occurred when he fell on his own knife, sparing the shy Boo from unwanted attention. Scout agrees, noting that to do otherwise would be “sort of like shootin’ a mockingbird.”", 1960, "Harper Lee", 'Gothic,', TRUE )
INSERT INTO books VALUES (4, '1984', "The book is set in 1984 in Oceania, one of three perpetually warring totalitarian states (the other two are Eurasia and Eastasia). Oceania is governed by the all-controlling Party, which has brainwashed the population into unthinking obedience to its leader, Big Brother. The Party has created a propagandistic language known as Newspeak, which is designed to limit free thought and promote the Party’s doctrines. Its words include doublethink (belief in contradictory ideas simultaneously), which is reflected in the Party’s slogans: “War is peace,” “Freedom is slavery,” and “Ignorance is strength.” The Party maintains control through the Thought Police and continual surveillance. The book’s hero, Winston Smith, is a minor party functionary living in a London that is still shattered by a nuclear war that took place not long after World War II. He belongs to the Outer Party, and his job is to rewrite history in the Ministry of Truth, bringing it in line with current political thinking. However, Winston’s longing for truth and decency leads him to secretly rebel against the government. He embarks on a forbidden affair with Julia, a like-minded woman, and they rent a room in a neighbourhood populated by Proles (short for proletariats). Winston also becomes increasingly interested in the Brotherhood, a group of dissenters. Unbeknownst to Winston and Julia, however, they are being watched closely (ubiquitous posters throughout the city warn residents that “Big Brother is watching you.”). When Winston is approached by O’Brien—an official of the Inner Party who appears to be a secret member of the Brotherhood—the trap is set. O’Brien is actually a spy for the Party, on the lookout for “thought-criminals,” and Winston and Julia are eventually caught and sent to the Ministry of Love for a violent reeducation. The ensuing imprisonment, torture, and reeducation of Winston are intended not merely to break him physically or make him submit but to root out his independence and destroy his dignity and humanity. In Room 101, where prisoners are forced into submission by exposure to their worst nightmares, Winston panics as a cage of rats is attached to his head. He yells out for his tormentors to “Do it to Julia!” and states that he does not care what happens to her. With this betrayal, Winston is released. He later encounters Julia, and neither is interested in the other. Instead Winston loves Big Brother." , 1948, "George Orwell", 'Science Fiction', FALSE)
INSERT INTO books VALUES (5, 'Pride and Prejudice',"The novel opens with one of the most famous lines in English literature: “It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.” The statement is seemingly what Mrs. Bennet thinks as she sets her sights on the newly arrived Bingley, who she is sure will make a suitable husband for one of her daughters. At a ball, Bingley takes an immediate interest in the beautiful and shy Jane. The encounter between his friend Darcy and Elizabeth is less cordial. Although Austen shows them intrigued by each other, she reverses the convention of first impressions: the pride of rank and fortune and prejudice against the social inferiority of Elizabeth’s family hold Darcy aloof, while the pride of self-respect and prejudice against Darcy’s snobbery hold Elizabeth equally aloof. The pompous Collins soon arrives, hoping to marry one of the Bennet sisters. Mrs. Bennet steers him toward Elizabeth, but the latter refuses his offer of marriage. He instead becomes engaged to her friend Charlotte. During this time, Elizabeth encounters the charming Wickham. There is a mutual attraction between the two, and he informs her that Darcy has denied him his inheritance. After Bingley abruptly departs for London, Elizabeth’s dislike of Darcy mounts as she becomes convinced that he is discouraging Bingley’s relationship with Jane. Darcy, however, has grown increasingly fond of Elizabeth, admiring her intelligence and vitality. While visiting the now-married Charlotte, Elizabeth sees Darcy, who professes his love for her and proposes. A surprised Elizabeth refuses his offer, and, when Darcy demands an explanation, she accuses him of breaking up Jane and Bingley and of denying Wickham his inheritance. Darcy subsequently writes Elizabeth a letter in which he explains that he separated the couple largely because he did not believe Jane returned Bingley’s affection. He also discloses that Wickham, after squandering his inheritance, tried to marry Darcy’s then 15-year-old sister in an attempt to gain possession of her fortune. With these revelations, Elizabeth begins to see Darcy in a new light. Shortly thereafter the youngest Bennet sister, Lydia, elopes with Wickham. The news is met with great alarm by Elizabeth, since the scandalous affair—which is unlikely to end in marriage—could ruin the reputation of the other Bennet sisters. When she tells Darcy, he persuades Wickham to marry Lydia, offering him money. Despite Darcy’s attempt to keep his intervention a secret, Elizabeth learns of his actions. At the encouragement of Darcy, Bingley subsequently returns, and he and Jane become engaged. Finally, Darcy proposes again to Elizabeth, who this time accepts.", 1813, "Jane Austen", 'Romance', TRUE )
INSERT INTO books VALUES (6, 'The Great Gatsby',"The Great Gatsby follows Nick Carraway, a young man from the midwest who moves to New York. He meets Jay Gatsby, a mysterious millionaire, and spends time with his cousin, Daisy, and her husband, Tom. As Nick learns more about the dynamic in East and West Egg, he also learns that Gatsby is in love with Daisy and wants Nick to help him rekindle their relationship. What at first seems like a perfect match soon results in a tragic event that should shatter the lives of everyone involved. But, as Nick learns, the people he’s surrounded himself with are vapid and entirely without empathy. " , 1925, "F. Scott Fitzgerald", "Tradgedy", TRUE)
INSERT INTO books VALUES (7, 'Macbeth',"Three witches tell the Scottish general Macbeth that he will be King of Scotland. Encouraged by his wife, Macbeth kills the king, becomes the new king, and kills more people out of paranoia. Civil war erupts to overthrow Macbeth, resulting in more death.", 1623, "William Shakespear", "Tragedy", FALSE)
INSERT INTO books VALUES (8, 'Jane Eyre', "The novel follows the story of Jane, a seemingly plain and simple girl as she battles through life's struggles. Jane has many obstacles in her life - her cruel and abusive Aunt Reed, the grim conditions at Lowood school, her love for Rochester and Rochester's marriage to Bertha. However, Jane overcomes these obstacles through her determination, sharp wit and courage. The novel ends with Jane married to Rochester with children of their own." , 1847, "Charlotte Bronte", "Romance", FALSE)
INSERT INTO books VALUES (9, 'The Lion, the Witch and the Wardrobe', "When the Pevensie children, Peter, Susan, Edmund, and Lucy are sent out of London during World War II, they have no idea of the magical journey they are beginning. In the darkness of the old country house where they are sent, the children stumble through an old wardrobe to the land of Narnia, where animals talk and magic exists." , 1950, "C.S Lewis", "Fantasy" ,FALSE)
INSERT INTO books VALUES (10, 'Lord of the Flies', "Lord of the Flies tells the story of a group of young boys who find themselves alone on a deserted island. They develop rules and a system of organization, but without any adults to serve as a civilizing impulse, the children eventually become violent and brutal" , 1954, "William Golding", "Dystopian", TRUE )
